spring:

    application.name: "api-consulta"

    data:
        rest:
            basePath: "/api"
            default-media-type: application/json
            return-body-on-create: true
            return-body-on-update: true
    jackson:
        default-property-inclusion: NON_NULL

    datasource:
        url: jdbc:postgresql://localhost:5432/creditosdb?currentSchema=creditos
        username: admin
        password: admin
        driver-class-name: org.postgresql.Driver
    
    flyway:
        baseline-on-migrate: true
        locations: classpath:db/migration

    jpa:
        hibernate:
            ddl-auto: none
        show-sql: true
        properties:
            hibernate.format_sql: true
            
    kafka:
        bootstrap-servers: localhost:9092
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8080

logging:
  level:
    org.springframework.aop: INFO
    org.springframework.beans.factory: INFO
    br.com.gestiona.apiconsulta: INFO